name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install root and workspaces dependencies
        run: npm install

      - name: Build Web & API workspaces
        run: npm run build

      - name: Run Jest Unit Tests for API
        run: npm run test --workspace=apps/api
